### ISSUE TITLE
ZeroDivisionError: division by zero

### ISSUE THREAD

**Issue by M-Amrollahi** [a1da4/sppmi-svd#7]
I got "division by zero" when I wanted to test the code. Do you know where the issue is :

```
python main.py -f wiki-article-100m.txt -w 5 -s 5 -d 300 -p dic_id2word.pkl
2021-05-02 10:39:23,017 [INFO] args: Namespace(cooccur_pretrained=None, dim=300, file_path='wiki-article-100m.txt', has_abs_dis=False, has_cds=False, pickle_id2word='dic_id2word.pkl', shift=5, sppmi_pretrained=None, threshold=0, window_size=5)
2021-05-02 10:39:23,017 [INFO] Loading dictionary...
2021-05-02 10:39:23,031 [INFO] Creating co-occur matrix...
2021-05-02 10:40:54,659 [INFO] Computing sppmi matrix...
  0%|                                                                                            | 0/13932 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "main.py", line 130, in <module>
    cli_main()
  File "main.py", line 126, in cli_main
    main(args)
  File "main.py", line 53, in main
    M = sppmi(C, args.shift, has_abs_dis=args.has_abs_dis, has_cds=args.has_cds)
  File "/home/x/Tests/sppmi-svd/util.py", line 153, in sppmi
    shifted_pmi = log2(Cwc * N_cds / (Nc[i] * Nc_cds[j]) + eps)
ZeroDivisionError: division by zero
```

**Comment by a1da4** [comment]
Dear Amrollahi,
Thank you for letting me know.
I fixed dividing zero problem in `util.py/sppmi`. https://github.com/a1da4/sppmi-svd/pull/8
