### ISSUE TITLE
ValueError: math domain error

### ISSUE THREAD

**Issue by M-Amrollahi** [a1da4/sppmi-svd#9]
I think the input of log is out of range:
```
(base) x@s ~/Tests/sppmi-svd $ python main.py -f wiki-article-100m.txt -p dic_id2word.pkl -w 10 -s 5 -d 300
2021-05-03 18:14:13,523 [INFO] args: Namespace(cooccur_pretrained=None, dim=300, file_path='wiki-article-100m.txt', has_abs_dis=False, has_cds=False, pickle_id2word='dic_id2word.pkl', shift=5, sppmi_pretrained=None, threshold=0, window_size=10)
2021-05-03 18:14:13,523 [INFO] Loading dictionary...
2021-05-03 18:14:13,537 [INFO] Creating co-occur matrix...
2021-05-03 18:16:42,296 [INFO] Computing sppmi matrix...
  0%|                                                                                                | 0/13932 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "main.py", line 130, in <module>
    cli_main()
  File "main.py", line 126, in cli_main
    main(args)
  File "main.py", line 53, in main
    M = sppmi(C, args.shift, has_abs_dis=args.has_abs_dis, has_cds=args.has_cds)
  File "/home/x/Tests/sppmi-svd/util.py", line 154, in sppmi
    shifted_pmi = log2(Cwc * N_cds / (Nc[i] * Nc_cds[j] + eps))
ValueError: math domain error
```

The issue is that I am going to see the results and also the performance of the method.
Regards

**Comment by a1da4** [comment]
I fix this error. https://github.com/a1da4/sppmi-svd/pull/10
I suspect there are words that do not co-occur with other target words at all, so wider window width or higher frequency threshold for target word selection in `make_id2word.py` (50 or 100) seems to work well.
